info:
  contact: {}
  description: This is a REST API built to keep track of whisky infinity bottles and
    their history
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Infinity Bottle API
  version: "1.0"
paths:
  /v1/contributions/{id}:
    get:
      description: Retrieve all information about an infinity bottle contribution
        by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get an infinity bottle contribution by ID
      tags:
      - contribution
  /v1/healthcheck:
    get:
      description: Perform a basic request to check if the service is available
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Basic healthcheck
      tags:
      - healthcheck
  /v1/infinitybottles/{id}:
    get:
      description: Retrieve all information about an infinity bottle by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get an infinity bottle by ID
      tags:
      - infinityBottle
swagger: "2.0"
