definitions:
  data.Contribution:
    properties:
      addedAt:
        type: string
      amount:
        type: integer
      brandName:
        type: string
      id:
        type: integer
      infinityBottleID:
        type: integer
      tags:
        items:
          type: string
        type: array
      version:
        type: integer
    type: object
  data.InfinityBottle:
    properties:
      bottleName:
        type: string
      contributions:
        items:
          $ref: '#/definitions/data.Contribution'
        type: array
      createdAt:
        type: string
      emptyStart:
        type: boolean
      id:
        type: integer
      numberOfContributions:
        type: integer
      updatedAt:
        type: string
      version:
        type: integer
    type: object
  main.ContributionPost:
    properties:
      amount:
        type: integer
      brandName:
        type: string
      infinityBottleID:
        type: integer
      tags:
        items:
          type: string
        type: array
    type: object
  main.ErrorMessage:
    properties:
      message: {}
    type: object
  main.HealthCheckMessage:
    properties:
      environment:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  main.InfinityBottlePost:
    properties:
      bottleName:
        type: string
      emptyStart:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a REST API built to keep track of whisky infinity bottles and
    their history
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Infinity Bottle API
  version: "1.0"
paths:
  /v1/contributions:
    post:
      consumes:
      - application/json
      description: Add a new contribution to an infinity bottle
      parameters:
      - description: New contribution to an infinity bottle
        in: body
        name: Contribution
        required: true
        schema:
          $ref: '#/definitions/main.ContributionPost'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.ContributionPost'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Add a new contribution to an infinity bottle
      tags:
      - contribution
  /v1/contributions/{id}:
    delete:
      description: Delete an infinity bottle contribution by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Delete an infinity bottle contribution by ID
      tags:
      - contribution
    get:
      description: Retrieve all information about an infinity bottle contribution
        by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Contribution'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Get an infinity bottle contribution by ID
      tags:
      - contribution
    put:
      description: Update all information about an infinity bottle contribution by
        ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update contribution to an infinity bottle
        in: body
        name: Contribution
        required: true
        schema:
          $ref: '#/definitions/main.ContributionPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Contribution'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Update an infinity bottle contribution by ID
      tags:
      - contribution
  /v1/healthcheck:
    get:
      description: Perform a basic request to check if the service is available
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthCheckMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Basic healthcheck
      tags:
      - healthcheck
  /v1/infinitybottles:
    get:
      description: List all infinity bottles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.InfinityBottle'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: List all infinity bottles
      tags:
      - infinityBottle
    post:
      consumes:
      - application/json
      description: Create a new infinity bottle
      parameters:
      - description: New infinity bottle
        in: body
        name: InfinityBottle
        required: true
        schema:
          $ref: '#/definitions/main.InfinityBottlePost'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.InfinityBottlePost'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Create a new infinity bottle
      tags:
      - infinityBottle
  /v1/infinitybottles/{id}:
    delete:
      description: Delete an infinity bottle by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Delete an infinity bottle by ID
      tags:
      - infinityBottle
    get:
      description: Retrieve all information about an infinity bottle by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.InfinityBottle'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Get an infinity bottle by ID
      tags:
      - infinityBottle
    put:
      description: Update all information about an infinity bottle by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update to an infinity bottle
        in: body
        name: InfinityBottle
        required: true
        schema:
          $ref: '#/definitions/main.InfinityBottlePost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.InfinityBottle'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Update an infinity bottle by ID
      tags:
      - infinityBottle
swagger: "2.0"
